### ISSUE TITLE
ISO19139 Json-schema creation

### ISSUE THREAD

**Issue by juanmav** [highsource/jsonix-schema-compiler#42]
Hi,

I trying to create the Json-schema of ISO19139 profile. 

```javascript
../jsonix/lib$ java -jar jsonix-schema-compiler-full.jar http://schemas.opengis.net/iso/19139/20060504/gmd/metadataEntity.xsd

Exception in thread "main" com.sun.tools.xjc.BadCommandLineException: unrecognized parameter -generateJsonSchema
        at com.sun.tools.xjc.Options.parseArguments(Options.java:814)
        at org.hisrc.jsonix.JsonixMain.main(JsonixMain.java:74)
```

Maybe this feature is not yet with jsonix distributions file ? But the compiler is executed without the generateJsonSchema parameter does not work either.

```javascript
../jsonix/lib$ java -jar jsonix-schema-compiler-full.jar http://schemas.opengis.net/iso/19139/20060504/gmd/metadataEntity.xsd
```

Any ideas ?

Thanks in advance
JM

**Comment by highsource** [comment]
You should `npm install jsonix-schema-compiler`. The JAR in Jsonix lib is not the actual as Jsonix was not released for quite a while already.

You're trying to compile an OGC Schema. :) This is extremely hard. You need a lot of carefully orchestrated configs and binding files to make it work. This is the scope of the `ogc-schemas` project. I'll add schema generation in one of the next versions. It's just too tricky - not because of Jsonix but mainly because of the underlying tech (JAXB/XJC).

**Comment by juanmav** [comment]
Yes, I know! :D

I started working with Json-schemas to auto-generate forms. I had nice results using [angular-schema-form](https://github.com/Textalk/angular-schema-form) with the business models on the project I am working on.

Well I just tried it! with ogc-schemas! :P

**Comment by highsource** [comment]
I'll close this since JSON Schemas area already generated in [ogc-schemas](https://github.com/highsource/ogc-schemas):

https://github.com/highsource/ogc-schemas/tree/master/scripts/jsonschemas
