### ISSUE TITLE
How to generate a json schema with the same specifications using a json payload?

### ISSUE THREAD

**Issue by tikaa** [highsource/jsonix-schema-compiler#65]
Hello,

I need to generate json schema from a json payload/ XML payload and XSD. I could observe with this library I can cover both XML and XSD as follows

XSD _-> directly use the library
XML -> convert to XSD using JAXB -> Use this library to generate JSON schema from XSD

I used some other online tools to generate json schema from json payload, but the schema specification is different. How can I use this library to generate the json schema for a json payload I have with me?

One option is the generate the XML payload for a json using org.json and then generate the corresponding XSD then convert it to json schema which is a tedious approach. 

Regards
Awanthika

**Comment by highsource** [comment]
No, this compiler is XML Schema first, it is not focused on JSON payloads.

I won't also recommend JSON->XML->XSD->JSON Schema. The resulting schema will not match the original JSON because it is derived from the XSD and the JSON you'll get is the one Jsonix would produce, not your original JSON (there may be deviations).

This is simply not the right tool for JSON-first schema generation.
